"""The scorer that runs in the endpoint, tested where scikit-learn is not installed.

**This is the whole reason the artefact is data.** Nothing here imports a model library, and
these tests run in the same offline suite as every claim harness. A pickle would have made this
file impossible: it could only have been tested by loading it, which needs the library, which
needs the version, which is the coupling `artefact.py` exists to remove.

The one thing these tests cannot show is that the scorer agrees with scikit-learn — that check
needs both, so it lives in `scripts/train_classifier.py` and gates the artefact's existence.
"""

from __future__ import annotations

import math

import pytest

from manifest.classification.artefact import VERSION, prior, scores, terms

#: Two headings, four features, hand-built. Small enough to compute the expected answer by hand,
#: which is the point: a fixture generated by the thing under test proves that it agrees with
#: itself.
ARTEFACT = {
    "version": VERSION,
    "ngram_max": 1,
    "sublinear_tf": True,
    "vocabulary": {"glazed": 0, "unglazed": 1, "tiles": 2},
    "idf": [2.0, 2.0, 1.0],
    "classes": ["690722", "690721"],
    "coefficients": [[3.0, -3.0, 0.0], [-3.0, 3.0, 0.0]],
    "intercepts": [0.0, 0.0],
    "minimum_score": 0.5,
}


def test_unigrams_and_bigrams_are_built_the_way_the_vectoriser_builds_them() -> None:
    assert terms("Glazed ceramic tiles", 2) == [
        "glazed",
        "ceramic",
        "tiles",
        "glazed ceramic",
        "ceramic tiles",
    ]


def test_single_characters_and_punctuation_are_not_features() -> None:
    """scikit-learn's default pattern needs two word characters. `5L` survives, `,` does not."""
    assert terms("Oil, 5L a tin", 1) == ["oil", "5l", "tin"]


def test_the_distinguishing_word_decides_the_ranking() -> None:
    assert scores(ARTEFACT, "glazed tiles")[0]["code"] == "690722"
    assert scores(ARTEFACT, "unglazed tiles")[0]["code"] == "690721"


def test_the_scores_are_a_distribution() -> None:
    """Softmax, not per-class sigmoid. The gap the contract's band is declared on depends on it."""
    assert sum(
        candidate["score"] for candidate in scores(ARTEFACT, "glazed tiles")
    ) == pytest.approx(1.0)


def test_a_description_with_no_distinguishing_word_splits_the_mass() -> None:
    """`tiles` carries no weight in either class, so neither is separated from the other.

    This is the property the whole classifier exists to demonstrate, at the smallest scale it can
    be shown: a description that omits the word that decides the heading does not get a winner.
    """
    ranked = scores(ARTEFACT, "tiles")
    assert ranked[0]["score"] - ranked[1]["score"] == pytest.approx(0.0)


def test_terms_outside_the_vocabulary_are_dropped_rather_than_counted() -> None:
    """An unfamiliar description scores the prior, not a confident guess."""
    ranked = scores(ARTEFACT, "marble slabs cut to size")
    assert ranked[0]["score"] == pytest.approx(prior(ARTEFACT))


def test_the_floor_is_what_the_model_gives_no_information() -> None:
    assert prior(ARTEFACT) == pytest.approx(0.5)


def test_a_repeated_term_is_dampened_rather_than_doubled() -> None:
    """Sublinear tf: the second mention of a word is worth less than the first.

    Checked because the flag is exported and read back, and reading it back wrong is invisible —
    the ranking barely moves and only the scores are off, which is exactly the class of defect
    that reaches production.
    """
    once = scores(ARTEFACT, "glazed tiles")[0]["score"]
    twice = scores(ARTEFACT, "glazed glazed tiles")[0]["score"]
    assert twice > once
    assert twice < scores({**ARTEFACT, "sublinear_tf": False}, "glazed glazed tiles")[0]["score"]


def test_an_artefact_from_a_different_layout_is_refused() -> None:
    with pytest.raises(ValueError, match="is not 1"):
        scores({**ARTEFACT, "version": 2}, "glazed tiles")


def test_a_large_linear_score_does_not_overflow() -> None:
    """`math.exp(800)` raises. The shift by the maximum is what stops the endpoint answering 500."""
    enormous = {**ARTEFACT, "intercepts": [900.0, 0.0]}
    ranked = scores(enormous, "tiles")
    assert ranked[0]["score"] == pytest.approx(1.0)
    assert not math.isnan(ranked[1]["score"])
