"""Claim 1's loop as the estate performs it: recorded decisions becoming labelled observations.

The mechanism is proved in `evals/feedback/` against decisions constructed from ground truth.
What is tested here is the adapter — that it reads the table this system actually writes, that
the policy comes from the contract rather than from the handler, and above all that a reviewer
who approves everything cannot feed the derivation that decides what publishes.
"""

from __future__ import annotations

import json
from decimal import Decimal
from typing import Any

import pytest

from manifest.handlers import harvest as harvest_handler


def _row(
    *,
    field: str,
    reviewer: str,
    decision: str,
    confidence: float,
    seconds: int = 30,
    agreed: bool | None = None,
) -> dict[str, Any]:
    return {
        "document_version": {"S": "v1"},
        "field": {"S": field},
        "document": {"S": "SHP00001-bill_of_lading"},
        "reviewer": {"S": reviewer},
        "decision": {"S": decision},
        "seconds_on_task": {"N": str(seconds)},
        "agreed_with_model": {"BOOL": (decision == "approved") if agreed is None else agreed},
        "confidence": {"N": str(confidence)},
    }


class _Table:
    def __init__(self, rows: list[dict[str, Any]]) -> None:
        self.rows = rows

    def get_paginator(self, _name: str) -> Any:
        return self

    def paginate(self, **_kwargs: Any) -> Any:
        return [{"Items": self.rows}]


class _Store:
    def __init__(self) -> None:
        self.puts: list[dict[str, Any]] = []

    def put_object(self, **kwargs: Any) -> dict[str, Any]:
        self.puts.append(kwargs)
        return {}


@pytest.fixture
def estate(monkeypatch: pytest.MonkeyPatch):
    store = _Store()
    monkeypatch.setenv("RECORDS_BUCKET", "manifest-records-111111111111")
    monkeypatch.setenv("DECISIONS_TABLE", "manifest-review-decisions")
    monkeypatch.setenv("DATA_KEY_ARN", "arn:aws:kms:eu-central-1:111111111111:key/abc")
    monkeypatch.setenv("CONTRACTS_DIR", "contracts")

    def _make(rows: list[dict[str, Any]]) -> _Store:
        table = _Table(rows)
        monkeypatch.setattr(
            harvest_handler, "_client", lambda name: table if name == "dynamodb" else store
        )
        return store

    return _make


READER = "reference-ocr@tesseract 5.5.0"


def test_a_correction_becomes_a_labelled_error(estate) -> None:
    """The strongest evidence this system will ever see: a human looked and said what it said."""
    store = estate(
        [_row(field="consignee", reviewer="eirini", decision="corrected", confidence=0.4)]
    )

    answer = harvest_handler.handler({"reader": READER})

    assert answer["observations"] == 1
    written = json.loads(store.puts[0]["Body"])
    assert written["from_corrections"] == 1
    assert written["observations"][0]["confidence"] == 0.4


def test_a_reviewer_who_approves_everything_is_excluded_and_counted(estate) -> None:
    """**The one that would poison the derivation this loop exists to feed.**

    A rubber stamp produces `CORRECT` observations at whatever confidence the model emitted; the
    observed error rate falls, the bound tightens, and the threshold drops on evidence nobody
    generated by looking at anything. Excluded — and counted, because a harvest that quietly lost
    its approvals is one whose N nobody can interpret.
    """
    store = estate(
        [
            _row(field="consignee", reviewer="stamp", decision="approved", confidence=0.5)
            for _ in range(40)
        ]
    )

    answer = harvest_handler.handler({"reader": READER})

    written = json.loads(store.puts[0]["Body"])
    assert written["excluded_rubber_stamped"] == 40
    assert answer["observations"] == 0
    assert answer["excluded"] == 40


def test_integrity_is_computed_over_every_decision_a_reviewer_made(estate) -> None:
    """A rubber stamp is a property of a person, not of a field.

    Measured per field, one careful field would hide a careless day — so the agreement rate is
    computed across everything this reviewer decided and then applied to each field's harvest.
    """
    rows = [
        _row(field="consignee", reviewer="stamp", decision="approved", confidence=0.5)
        for _ in range(30)
    ]
    rows += [
        _row(field="gross_weight", reviewer="stamp", decision="approved", confidence=0.6)
        for _ in range(30)
    ]
    store = estate(rows)

    harvest_handler.handler({"reader": READER})

    for put in store.puts:
        assert json.loads(put["Body"])["excluded_rubber_stamped"] > 0


def test_a_row_with_no_confidence_is_skipped_and_reported(estate) -> None:
    """Rows written before the column existed. Skipped, and the count says so.

    An observation without the confidence the model had at queue time is a label with nothing to
    calibrate against, and inventing one would put a point on the curve at a place nothing
    measured.
    """
    row = _row(field="consignee", reviewer="eirini", decision="corrected", confidence=0.4)
    del row["confidence"]
    estate([row])

    answer = harvest_handler.handler({"reader": READER})

    assert answer["decisions_read"] == 1
    assert answer["decisions_unreadable"] == 1
    assert answer["observations"] == 0


def test_a_supplied_value_is_not_evidence_about_the_reader(estate) -> None:
    """The field had no provenance, so there was no model value to be right or wrong about.

    Counting it would credit the reader with a human's work — which is the same error as the
    rubber stamp, pointed at the other side of the loop.
    """
    store = estate([_row(field="shipper", reviewer="eirini", decision="supplied", confidence=0.0)])

    answer = harvest_handler.handler({"reader": READER})

    assert answer["observations"] == 0
    assert json.loads(store.puts[0]["Body"])["excluded_no_provenance"] == 1


def test_the_evidence_is_keyed_by_the_reader_that_produced_the_confidences(estate) -> None:
    """An observation is a statement about a reader at a version.

    Pooling two readers' evidence under one field would calibrate a curve neither of them
    produced — the same reason the ledger is keyed by `(document, reader)`.
    """
    store = estate(
        [_row(field="consignee", reviewer="eirini", decision="corrected", confidence=0.4)]
    )

    harvest_handler.handler({"reader": READER})

    assert store.puts[0]["Key"] == f"feedback/{READER}/consignee.json"


def test_a_harvest_that_names_no_reader_is_refused(estate) -> None:
    estate([])

    with pytest.raises(harvest_handler.HandlerError, match="reader"):
        harvest_handler.handler({})


def test_the_policy_comes_from_the_contract_and_not_from_the_handler(estate) -> None:
    """What counts as a human looking is a declared policy. A default here would be this
    handler quietly setting it."""
    estate([])

    maximum, minimum = harvest_handler._policy()

    assert 0 < maximum <= 1
    assert minimum > Decimal("0")
