"""Turn recorded human decisions into labelled observations, and say what was excluded.

**Claim 1's loop, on the estate.** `core/feedback.py` has existed since the calibration was
written and nothing in the running system ever called it: `evals/feedback/` drives it against
decisions constructed from ground truth, which demonstrates the mechanism and measures nothing.
So *"a field can leave always-review as N grows"* was a property of a pure function and an
untested property of the system — the same state claims 4, 5 and 6 were in this morning.

The source now exists. `handlers/decide.py` writes a row per decision, with the reviewer, the
outcome, the seconds and **the confidence the model had when the item was queued**. That last
one is the x-axis of the whole calibration, and it is recorded at decision time rather than
looked up afterwards, because a value re-read in between would be a label calibrated against a
number nobody had when the human was looking.

**This handler decides nothing.** `core.feedback.harvest` decides which decisions are evidence;
the policy it filters against — the rubber-stamp agreement rate and the minimum seconds — is data
in `contracts/review/capacity.yaml`. What runs here is the read, the grouping, and the write.

**It harvests; it does not move a threshold.** The observations are written to the records
bucket and nothing else happens. Deriving a threshold here would put the evidence inside the
runtime and invite something there to re-derive from it, which is exactly what decision 20
forbids — every threshold in this repository comes from a committed recording, through a
ceremony that prints the movement of every field before it will overwrite anything.
`scripts/feedback_movement.py` is that ceremony's other half, and it is where a field leaving
always-review becomes visible.

**The exclusions are counted and named, never silently dropped.** An approval from a reviewer who
approves everything is not evidence: it produces a stream of `CORRECT` observations at whatever
confidence the model emitted, the observed error rate falls, and the threshold drops on evidence
nobody generated by looking at anything. `core.feedback` refuses those — and a harvest that
quietly lost 40% of its approvals is a harvest whose N nobody can interpret, so the count travels
with the output.
"""

from __future__ import annotations

import json
import os
from collections import defaultdict
from decimal import Decimal
from pathlib import Path
from typing import Any

from manifest.core.feedback import ReviewerIntegrity, harvest
from manifest.core.review import Decision, Record

#: Where the harvested evidence lands. Keyed by the reader identity that produced the
#: confidences, because an observation is a statement about *a reader at a version* — pooling
#: two readers' evidence under one field would calibrate a curve nothing produced.
PREFIX = "feedback"


class HandlerError(RuntimeError):
    """Refusal."""


def _client(name: str) -> Any:
    import boto3  # noqa: PLC0415 - the offline suite imports this module without AWS
    from botocore.config import Config  # noqa: PLC0415

    return boto3.client(
        name, config=Config(connect_timeout=5, read_timeout=60, retries={"max_attempts": 3})
    )


def _env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise HandlerError(f"{name} is not set; refused rather than defaulted")
    return value


def _policy() -> tuple[float, Decimal]:
    """The rubber-stamp rate and the minimum seconds, from the review contract.

    Read rather than defaulted. A default here would be this handler quietly setting the policy
    for what counts as a human looking, which is the one thing doctrine rule 2 turns on.
    """
    import yaml  # noqa: PLC0415

    text = Path(os.environ.get("CONTRACTS_DIR", "/var/task/contracts"), "review/capacity.yaml")
    loaded = yaml.safe_load(text.read_text(encoding="utf-8")) or {}
    for required in ("rubber_stamp_agreement_rate", "minimum_seconds_on_task"):
        if required not in loaded:
            raise HandlerError(
                f"contracts/review/capacity.yaml declares no {required}. The filter that decides "
                f"whether a human was looking is a policy, and it is not this handler's to pick"
            )
    return (
        float(loaded["rubber_stamp_agreement_rate"]),
        Decimal(str(loaded["minimum_seconds_on_task"])),
    )


def _decisions(table: str) -> list[dict[str, Any]]:
    """Every recorded decision. A scan, bounded by how many people are looking rather than by
    how many documents there are."""
    rows: list[dict[str, Any]] = []
    for page in _client("dynamodb").get_paginator("scan").paginate(TableName=table):
        rows.extend(page.get("Items", []))
    return rows


def _as_record(row: dict[str, Any]) -> tuple[Record, float] | None:
    """One row as `core.review.Record` and the confidence it was decided at.

    Returns `None` for a row this cannot read as evidence, and the two cases are different: a
    decision word the enum does not know is a schema this handler no longer understands, and a
    row with no confidence predates the column. Both are skipped and both are counted by the
    caller — an evidence set that silently shrank is one whose N means nothing.
    """
    try:
        decision = Decision(str(row["decision"]["S"]))
    except (KeyError, ValueError):
        return None
    if "confidence" not in row:
        return None
    return (
        Record(
            document=str(row.get("document", {}).get("S", "")),
            field=str(row["field"]["S"]),
            reviewer=str(row["reviewer"]["S"]),
            decision=decision,
            value=(row.get("value", {}).get("S")),
            seconds_on_task=Decimal(str(row.get("seconds_on_task", {}).get("N", "0"))),
            agreed_with_model=bool(row.get("agreed_with_model", {}).get("BOOL", False)),
        ),
        float(row["confidence"]["N"]),
    )


def _integrity(pairs: list[tuple[Record, float]]) -> dict[str, ReviewerIntegrity]:
    """What is known about each reviewer, as counts.

    Counts rather than a verdict, because the threshold for *was this person looking* is a
    declared policy and `core.feedback` applies it. Computed over **every** decision this
    reviewer made, not only the ones for the field being harvested: a rubber stamp is a property
    of a person, and measuring it per field would let one careful field hide a careless day.
    """
    decided: dict[str, int] = defaultdict(int)
    agreed: dict[str, int] = defaultdict(int)
    seconds: dict[str, Decimal] = defaultdict(Decimal)
    for record, _ in pairs:
        decided[record.reviewer] += 1
        agreed[record.reviewer] += int(record.agreed_with_model)
        seconds[record.reviewer] += record.seconds_on_task
    return {
        reviewer: ReviewerIntegrity(
            reviewer,
            decided[reviewer],
            agreed[reviewer],
            (seconds[reviewer] / Decimal(decided[reviewer])) if decided[reviewer] else Decimal("0"),
        )
        for reviewer in decided
    }


def handler(event: dict[str, Any], _context: Any = None) -> dict[str, Any]:
    """`{reader}` — harvest every decision into observations, per field, for that reader."""
    reader = str(event.get("reader") or "")
    if not reader:
        raise HandlerError(
            "give {'reader': '<identity>'}. An observation is a statement about a reader at a "
            "version, and a harvest that did not name one would pool evidence from two readers "
            "into a curve neither of them produced"
        )

    maximum_agreement_rate, minimum_seconds = _policy()
    rows = _decisions(_env("DECISIONS_TABLE"))
    pairs = [pair for pair in (_as_record(row) for row in rows) if pair is not None]
    unreadable = len(rows) - len(pairs)

    integrity = _integrity(pairs)
    by_field: dict[str, list[tuple[Record, float]]] = defaultdict(list)
    for record, confidence in pairs:
        by_field[record.field].append((record, confidence))

    bucket = _env("RECORDS_BUCKET")
    harvested = []
    for field, decisions in sorted(by_field.items()):
        gathered = harvest(
            field=field,
            decisions=decisions,
            integrity=integrity,
            maximum_agreement_rate=maximum_agreement_rate,
            minimum_seconds=minimum_seconds,
        )
        body = {
            "field": field,
            "reader": reader,
            "observations": [
                {"confidence": observation.confidence, "outcome": str(observation.outcome)}
                for observation in gathered.observations
            ],
            "from_corrections": gathered.from_corrections,
            "from_rejections": gathered.from_rejections,
            "from_approvals": gathered.from_approvals,
            "excluded_rubber_stamped": gathered.excluded_rubber_stamped,
            "excluded_too_fast": gathered.excluded_too_fast,
            "excluded_no_provenance": gathered.excluded_no_provenance,
            "summary": gathered.summary(),
        }
        _client("s3").put_object(
            Bucket=bucket,
            Key=f"{PREFIX}/{reader}/{field}.json",
            Body=json.dumps(body, indent=1).encode("utf-8"),
            ContentType="application/json",
            ServerSideEncryption="aws:kms",
            SSEKMSKeyId=_env("DATA_KEY_ARN"),
        )
        harvested.append(
            {
                "field": field,
                "observations": gathered.total,
                "excluded": gathered.excluded,
                "summary": gathered.summary(),
            }
        )

    return {
        "reader": reader,
        "decisions_read": len(rows),
        # Named rather than folded into a total. A row this cannot read is a schema question,
        # and a harvest that reported only what it managed to use would hide one.
        "decisions_unreadable": unreadable,
        "reviewers": len(integrity),
        "fields": len(harvested),
        "observations": sum(entry["observations"] for entry in harvested),
        "excluded": sum(entry["excluded"] for entry in harvested),
        "harvested": harvested,
    }
