#!/usr/bin/env python3
"""Create the document-automation project tier 2 reads through, because Terraform cannot.

**This is an exception to "IaC only", and it is written down rather than quietly taken.**
The AWS Terraform provider declares no resource for a Bedrock Data Automation project — checked
against `hashicorp/aws ~> 6.0` on 2026-08-13, whose only matching resources are Security Hub's.
Neither does CloudFormation. So the choice was between a tier that cannot run and a resource the
deploy creates itself, and this file is the second one: idempotent, invoked from `deploy.yml`
beside the layer that needs it, deleted by `destroy.yml`, with its whole configuration here in
one screen rather than in a console somebody clicked.

**Why the public project will not do**, which is the interesting half. AWS ships
`public-default`, and its standard output is `PAGE` and `ELEMENT` granularity with
**`boundingBox: DISABLED`**. Read from the API rather than assumed:

    granularity: {types: [PAGE, ELEMENT]}, boundingBox: {state: DISABLED}

A reading with no boxes cannot carry provenance, and claim 2 is that *every published field
traces to a page and a bounding box*. `extraction/aws/bda.py` refuses a response with no
`text_words` for exactly this reason — reconstructing words by splitting a line invents a box per
word, and an invented box is a provenance record pointing somewhere nobody measured. So the
project this project uses turns both on, and that is the only reason it exists.

**What it does not turn on.** `generativeField` stays disabled: a summary of a customs document,
generated by a model, sitting in the same payload as measured text is the one thing that would
make a reader unable to tell which is which.
"""

from __future__ import annotations

import argparse

#: The name the estate looks for. Stable, so a second deploy finds the first deploy's project
#: rather than making another — this script is idempotent by *name*, because BDA gives the ARN
#: an identifier the caller does not choose.
PROJECT_NAME = "manifest-word-provenance"

GREEN, DIM, RESET = "\033[32m", "\033[2m", "\033[0m"

#: What tier 2 must return for this repository to be able to use it at all.
#:
#: `WORD` is the granularity `bda.to_document` requires and `boundingBox` is what makes a word a
#: provenance record rather than a string. `LINE` comes with them because the adapter uses line
#: identity for reading order, and reconstructing that from word positions would be a second
#: guess at something the service already knows.
STANDARD_OUTPUT = {
    "document": {
        "extraction": {
            "granularity": {"types": ["PAGE", "ELEMENT", "WORD", "LINE"]},
            "boundingBox": {"state": "ENABLED"},
        },
        # Off. A generated summary of a customs document in the same payload as measured text is
        # the one addition that would stop a reader telling the two apart.
        "generativeField": {"state": "DISABLED"},
        "outputFormat": {
            "textFormat": {"types": ["PLAIN_TEXT"]},
            "additionalFileFormat": {"state": "DISABLED"},
        },
    }
}


def _client():
    import boto3  # noqa: PLC0415 - the offline suite imports this module without AWS

    return boto3.client("bedrock-data-automation")


def _existing(client) -> str:
    """This project's ARN, or `""`. Matched by name, which is the only stable handle there is."""
    paginator = client.get_paginator("list_data_automation_projects")
    for page in paginator.paginate(resourceOwner="ACCOUNT"):
        for project in page.get("projects", []):
            if project.get("projectName") == PROJECT_NAME:
                return str(project["projectArn"])
    return ""


def create(client) -> str:
    """Create it, or bring the existing one up to this configuration and return its ARN.

    Updated rather than left alone when it already exists: a project created by an older revision
    of this file would silently keep an older standard output, and the failure is a tier that
    returns text with no boxes — which `bda.to_document` refuses, three layers from here, in a
    message about a response shape.
    """
    arn = _existing(client)
    if arn:
        client.update_data_automation_project(
            projectArn=arn,
            standardOutputConfiguration=STANDARD_OUTPUT,
        )
        print(f"  {GREEN}ok{RESET}    {PROJECT_NAME} already exists; configuration reapplied")
        return arn

    created = client.create_data_automation_project(
        projectName=PROJECT_NAME,
        projectDescription=(
            "Word granularity with bounding boxes, which is what claim 2 needs and what the "
            "public default project does not provide."
        ),
        projectStage="LIVE",
        standardOutputConfiguration=STANDARD_OUTPUT,
    )
    print(f"  {GREEN}ok{RESET}    created {PROJECT_NAME}")
    return str(created["projectArn"])


def delete(client) -> int:
    """Remove it, and say so when there was nothing to remove.

    **A create path with no delete path is how an estate gets left standing** — the same rule
    the deploy and destroy workflows follow, applied to the one resource Terraform does not
    manage. Terraform would have taken this with the layer; nothing does, so `destroy.yml` must.
    """
    arn = _existing(client)
    if not arn:
        print(f"  {DIM}nothing to delete: no project named {PROJECT_NAME}{RESET}")
        return 0
    client.delete_data_automation_project(projectArn=arn)
    print(f"  {GREEN}ok{RESET}    deleted {arn}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--delete", action="store_true", help="Remove it. Used by the teardown.")
    parser.add_argument(
        "--print-arn",
        action="store_true",
        help="Print only the ARN, for a workflow to capture.",
    )
    arguments = parser.parse_args(argv)

    client = _client()
    if arguments.delete:
        return delete(client)

    arn = create(client)
    if arguments.print_arn:
        print(arn)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
