"""A reviewer's decision becoming a labelled observation, and the one rule that keeps it honest.

Claim 1 was a **snapshot**: thresholds derived once, from one recording, at one moment. Thirty-two
of thirty-six fields came out `always-review`, and the derivation was explicit about why — they
are **evidence-limited**, not quality-limited. The reader is not wrong; there is not enough
labelled data to prove it right at the budgets those fields declare.

The labelled data those fields need is being produced every day and thrown away. A reviewer
looking at a crop and typing the correct value has produced the highest-quality label this system
will ever see: a human looked at the page and said what it said. This module turns that into an
observation, so a field can *leave* always-review as N grows — which is claim 1 becoming a loop
rather than a photograph.

**The one rule, and it is the whole of the safety argument.**

A correction changes **N**. It never changes an error budget, and it never changes a threshold
directly. The budget is a declaration about acceptable harm — it comes from the domain, not from
how the month went — and a system that could relax it in response to queue pressure would have
inverted the derivation exactly as ADR-0001 forbids. What corrections do is add evidence; what
evidence does is let the *existing* budget be met at a lower threshold, or not.

Stated as a shape: `corrections → observations → N → derive(budget) → threshold`. There is no
arrow from corrections to budget, and `evals/review/` has a mutation that plants one.

**Which decisions count as evidence, and which do not.**

- **`CORRECTED` → an observation, outcome `WRONG`.** The reviewer saw the model's value and
  replaced it: a labelled error at a known confidence, which is the strongest evidence there is.
- **`REJECTED` → an observation, outcome `WRONG`.** Weaker — no ground truth came with it — but
  the outcome is known, and the outcome is what the derivation counts.
- **`APPROVED` → an observation, outcome `CORRECT`, *only if the reviewer was looking*.** See
  below; this is the one that can poison the derivation.
- **`SUPPLIED` → nothing.** The field had no provenance, so there was no model value to be right
  or wrong about. Counting it would credit the reader with a human's work.

**An approval from a rubber stamp is not evidence, and admitting one is how this module would
poison the very derivation it exists to feed.** A reviewer who approves everything produces a
stream of `CORRECT` observations at whatever confidence the model happened to emit, the observed
error rate falls, the upper bound tightens, and the threshold drops — on evidence that nobody
generated by looking at anything. So approvals are admitted only from reviewers who pass the
integrity checks `core.review` already computes, and the filtered count is **reported**, not
silently dropped: a corpus that quietly lost 40% of its approvals is a corpus whose N nobody can
interpret.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from manifest.core.calibration import Observation, Outcome
from manifest.core.review import Decision, Record


@dataclass(frozen=True, slots=True)
class ReviewerIntegrity:
    """What is known about a reviewer, as counts rather than as a verdict.

    Counts rather than a boolean because the threshold for "was this person looking" is a
    declared policy (`contracts/review/`), and a module that baked one in would be making that
    policy in a place nobody reviews.
    """

    reviewer: str
    decisions: int
    agreements: int
    median_seconds: Decimal

    @property
    def agreement_rate(self) -> float:
        return self.agreements / self.decisions if self.decisions else 0.0


@dataclass(frozen=True, slots=True)
class Harvest:
    """Observations gathered from review, and everything that was left out.

    Every excluded category is counted and named. An N that grew is only interpretable next to
    what did not contribute to it — and "we dropped some" is the shape under which a silent
    filter change moves every threshold in the repository.
    """

    field: str
    observations: tuple[Observation, ...]
    from_corrections: int
    from_rejections: int
    from_approvals: int
    excluded_rubber_stamped: int
    excluded_too_fast: int
    excluded_no_provenance: int

    @property
    def total(self) -> int:
        return len(self.observations)

    @property
    def excluded(self) -> int:
        return self.excluded_rubber_stamped + self.excluded_too_fast + self.excluded_no_provenance

    def summary(self) -> str:
        return (
            f"{self.field}: +{self.total} observation(s) "
            f"({self.from_corrections} corrected, {self.from_rejections} rejected, "
            f"{self.from_approvals} approved) — excluded {self.excluded} "
            f"({self.excluded_rubber_stamped} rubber-stamped, "
            f"{self.excluded_too_fast} below minimum time, "
            f"{self.excluded_no_provenance} supplied without provenance)"
        )


def harvest(
    *,
    field: str,
    decisions: list[tuple[Record, float]] | tuple[tuple[Record, float], ...],
    integrity: dict[str, ReviewerIntegrity],
    maximum_agreement_rate: float,
    minimum_seconds: Decimal,
) -> Harvest:
    """Turn recorded decisions into observations, and say what was left out.

    `decisions` pairs each record with the **confidence the model had when the item was
    queued**. That number is the x-axis of the whole calibration: an observation without it is a
    label with nothing to calibrate against, and reconstructing it later from the record would
    mean trusting that nothing re-read the page in between.

    `maximum_agreement_rate` and `minimum_seconds` are passed in from `contracts/review/`
    rather than defaulted here. A default would be this module quietly setting the policy for
    what counts as a human looking.
    """
    observations: list[Observation] = []
    corrections = rejections = approvals = 0
    rubber_stamped = too_fast = no_provenance = 0

    for record, confidence in decisions:
        if record.decision is Decision.SUPPLIED:
            # The reviewer located a value the system never proposed. There is no model output
            # here to be right or wrong about, so it is not an observation about the reader —
            # counting it as one would credit the reader with a human's work.
            no_provenance += 1
            continue

        if record.seconds_on_task < minimum_seconds:
            # Below the declared floor for a decision anybody could have made by looking. Not an
            # accusation about a person: it is a decision this system cannot treat as evidence,
            # and the count is reported so that a *pattern* of them is visible.
            too_fast += 1
            continue

        if record.decision is Decision.APPROVED:
            profile = integrity.get(record.reviewer)
            if profile is not None and profile.agreement_rate >= maximum_agreement_rate:
                # The poisoning path this module exists to close. A reviewer who agrees with
                # everything emits `CORRECT` at whatever confidence the model produced; the
                # observed error rate falls, the bound tightens, and the threshold drops on
                # evidence nobody generated by looking.
                rubber_stamped += 1
                continue
            observations.append(Observation(confidence=confidence, outcome=Outcome.CORRECT))
            approvals += 1
            continue

        if record.decision is Decision.CORRECTED:
            observations.append(Observation(confidence=confidence, outcome=Outcome.WRONG))
            corrections += 1
            continue

        if record.decision is Decision.REJECTED:
            observations.append(Observation(confidence=confidence, outcome=Outcome.WRONG))
            rejections += 1

    return Harvest(
        field=field,
        observations=tuple(observations),
        from_corrections=corrections,
        from_rejections=rejections,
        from_approvals=approvals,
        excluded_rubber_stamped=rubber_stamped,
        excluded_too_fast=too_fast,
        excluded_no_provenance=no_provenance,
    )


@dataclass(frozen=True, slots=True)
class Movement:
    """What the added evidence did to one field's threshold."""

    field: str
    before: float | None
    after: float | None
    observations_before: int
    observations_after: int
    #: The budget, carried through both derivations. Recorded so that a reader can see it did
    #: not move — which is the property this whole module rests on.
    error_budget: Decimal

    @property
    def left_always_review(self) -> bool:
        return self.before is None and self.after is not None

    @property
    def returned_to_always_review(self) -> bool:
        """Possible, and it is a *finding* rather than a regression.

        More evidence can show that a threshold which fitted at small N does not fit at large N.
        A system that could only ever loosen would be one whose evidence only ever pointed one
        way, which is not how evidence works.
        """
        return self.before is not None and self.after is None

    def describe(self) -> str:
        def show(value: float | None) -> str:
            return "always-review" if value is None else f"{value:.3f}"

        return (
            f"{self.field}: {show(self.before)} (N={self.observations_before}) → "
            f"{show(self.after)} (N={self.observations_after}), "
            f"budget {self.error_budget} unchanged"
        )


def movement(
    *,
    field: str,
    error_budget: Decimal,
    before: list[Observation] | tuple[Observation, ...],
    added: list[Observation] | tuple[Observation, ...],
) -> Movement:
    """Derive twice — once on the original evidence, once with the harvest added.

    The budget is passed **once** and used for both derivations. That is not a convenience: it
    is the guarantee, expressed as a signature. There is no parameter here through which a
    correction could reach a budget, so there is no code path through which queue pressure could
    relax one.
    """
    from manifest.core.calibration import derive  # noqa: PLC0415 - avoids a circular import

    first = derive(field, list(before), error_budget)
    second = derive(field, [*before, *added], error_budget)
    return Movement(
        field=field,
        before=first.value,
        after=second.value,
        observations_before=first.observations,
        observations_after=second.observations,
        error_budget=error_budget,
    )
